# Generated by Django 3.1.7 on 2021-06-03 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drfAPIView', '0002_remove_note_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Note',
            new_name='NoteModel',
        ),
    ]
